#%RAML 1.0 NamedExample
value:
  -
    ID: 123
    fname: parker
    lname: stark
    loc: BLR
    doj: 2020/10/19
    ctc:
      basic: 10000
      hra:  5000
      cvc: 1000
      sa: 10000
      pf: 2000
  -
    ID: 124
    fname: parker1
    lname: stark1
    loc: DHL
    doj: 2020/10/19
    ctc:
      basic: 20000
      hra:  5000
      cvc: 1000
      sa: 15000
      pf: 2000